create table if not exists public.providers (
  id bigint generated by default as identity primary key,
  name text not null,
  service text not null,
  category text not null,
  municipality text not null,
  rating numeric(2,1) not null default 5.0 check (rating between 0 and 5),
  completed_jobs integer not null default 0,
  starting_price integer not null check (starting_price >= 0),
  initials varchar(3) not null,
  color varchar(7) not null default '#0c789d',
  verified boolean not null default false,
  created_at timestamptz not null default now(),
  unique(name, service, municipality)
);

create table if not exists public.bookings (
  id bigint generated by default as identity primary key,
  reference varchar(12) unique not null,
  provider_id bigint not null references public.providers(id),
  customer_name text not null,
  email text not null,
  phone text not null,
  municipality text not null,
  preferred_date date not null,
  details text not null,
  status text not null default 'pending' check (status in ('pending','confirmed','completed','cancelled')),
  created_at timestamptz not null default now()
);

alter table public.providers enable row level security;
alter table public.bookings enable row level security;

insert into public.providers (name, service, category, municipality, rating, completed_jobs, starting_price, initials, color, verified) values
('Rico Mendoza','Aircon cleaning & repair','Home repair','Olongapo',4.9,87,650,'RM','#0c789d',true),
('Liza Cruz','Home deep cleaning','Cleaning','Subic',4.8,64,800,'LC','#d07645',true),
('Jun Alonzo','Electrical repair','Home repair','Castillejos',5.0,41,500,'JA','#567945',true),
('Mara Bautista','Event photography','Events','Iba',4.9,52,2500,'MB','#7560a8',true),
('Dario Villanueva','Plumbing services','Home repair','Botolan',4.7,38,550,'DV','#397d79',true),
('Ana Santos','Makeup & hair styling','Events','San Marcelino',4.9,73,1200,'AS','#b34d72',true)
on conflict do nothing;
